project:
  type: website
  output-dir: docs

website:
  title: "PowerSpectR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/RafaelSdeSouza/PowerSpectR
  page-footer:
    left: "PowerSpectR for robust image power spectra"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
